### ISSUE TITLE
ModuleNotFoundError: No module named 'bulk_update'

### ISSUE THREAD

**Issue by sethlivingston** [mathandpencil/django-bulk-sync#1]
After running `pipenv install django-bulk-sync` and running the app, I get the following error. I believe this is because bulk_update is not listed as a dependency for django-bulk-sync?

```
  ...
  File "C:\Users\under\.virtualenvs\truman-YgTzlGPJ\lib\site-packages\bulk_sync\__init__.py", line 5, in <module>
    from bulk_update.helper import bulk_update
ModuleNotFoundError: No module named 'bulk_update'
```

**Comment by ses4j** [comment]
Merged PR to fix.  `django_bulk_update` changed their package name.
