### ISSUE TITLE
many to many set error

### ISSUE THREAD

**Issue by hyusetiawan** [mathandpencil/django-bulk-sync#12]
I am using the library to bulk_sync a model that has a many to many to another model (embeds). Currently, bulk_sync fails due to django many to many set behavior:
`TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use embeds.set() instead.`
it seems bulk_sync could be extended to take into account a use case for this where given the model it can call a .set()?

**Comment by ses4j** [comment]
@hyusetiawan Can you provide a unit test that demonstrates the problem, possibly as a PR?

**Comment by ses4j** [comment]
Closing.  Please reopen with a unit test showing the issue.
