### ISSUE TITLE
empty list

### ISSUE THREAD

**Issue by hyusetiawan** [mathandpencil/django-bulk-sync#13]
if you bulk_sync an empty list (with the expectation of deletion of the items), bulk_sync will fail with the following error message:
```
File "/usr/local/lib/python3.8/site-packages/bulk_sync/__init__.py", line 22, in bulk_sync
    db_class = new_models[0].__class__
IndexError: list index out of range
```

**Comment by ses4j** [comment]
@hyusetiawan Please see #11, I think that is the same issue.  Interested in comments, there.
