### ISSUE TITLE
Exclude fields from updates

### ISSUE THREAD

**Issue by VKFisher** [mathandpencil/django-bulk-sync#15]
In a project I'm working on there are models with around 50 fields and I want to update most of them except for a couple. This prompted me to add this bit of code:

```python
    if exclude_fields is not None:
        # exlude some fields from updates
        fields_set = set(fields)
        exclude_fields_set = set(exclude_fields)

        if not exclude_fields_set.issubset(fields_set):
            raise Exception(
                f'Cannot exclude field(s) {exclude_fields_set - fields_set} '
                f'as they are not present on model "{db_class.__name__}"'
            )

        fields = [
            field for field in fields_set
            if field not in exclude_fields_set
        ]
```

Should I create a pull request to add this functionality to `bulk_sync`? It technically accomplishes the same thing as the `fields` argument, but I think the convenience might make it a worthwhile addition.

**Comment by ses4j** [comment]
Sure, I think that's reasonable. Thanks!

**Comment by ses4j** [comment]
Releasing in 3.1.
