### ISSUE TITLE
bulk_compare AttributeError: 'OneToOneRel' object has no attribute 'attname'

### ISSUE THREAD

**Issue by rustanacexd** [mathandpencil/django-bulk-sync#20]
How to handle one to one reverse relationship in ignored_fields when using `bulk_compare`? So reverse one to one relationship is `obj.weeklyptoaccrualsyncprofile` for this model, so I passed `ignore_fields=["weeklyptoaccrualsyncprofile_id"]` but I am getting this error ``` AttributeError: 'OneToOneRel' object has no attribute 'attname```

I also tried passing `ignore_fields=["weeklyptoaccrualsyncprofile"]` and still the same error.

Thoughts?

**Comment by ses4j** [comment]
@rustanacexd If you can create a working example or a failing unit test demonstrating this, I am happy to take a look.

**Comment by ses4j** [comment]
Closing as inactive.
