### ISSUE TITLE
bulk_sync does not account for potential field value changes during save to db

### ISSUE THREAD

**Issue by VKFisher** [mathandpencil/django-bulk-sync#21]
Let's say we have a model with a FloatField
```python
class TestModel(models.Model):
    float_value = models.FloatField()
```

And we instantiate it with a serialized value
```python
new_test_model_instance=TestModel(float_value='123.456')
```

This is fine, since while saving the instance to database django passes this value through `FloatField.to_python()` which converts it to `float`.  However, if we pass the unsaved instance to `bulk_sync`
```python
bulk_sync(
    [new_test_model_instance],
    key_fields=('float_value',),
    filters=None,
)
```
 the key tuple generated by `get_key()` will contain the string representation, while the key tuples of database objects in `obj_dict` will contain floats, so `bulk_sync` will fail to match the new instance with an existing one even if the actual values of the `float_value` field are the same.

A potential solution would be to pass values to the respective fields' `to_python()` methods when generating the key tuples of the new model instances

**Comment by ses4j** [comment]
Fixed with 3.2.0. Thanks for PR.
