### ISSUE TITLE
Django 2.2 officially introduced a bulk_update() method

### ISSUE THREAD

**Issue by vberlier** [mathandpencil/django-bulk-sync#4]
Hello,

Django 2.2 officially introduced a [bulk_update](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#bulk-update) method on querysets so I was wondering if it would be possible to use it instead of relying on the `django-bulk-update` package.

Thanks for all your hard work :)

**Comment by keyz182** [comment]
Put in a draft PR #5 for this.

**Comment by ses4j** [comment]
Merged into v2.0.
