### ISSUE TITLE
Manager' object has no attribute 'bulk_update'

### ISSUE THREAD

**Issue by manojsitapara** [mathandpencil/django-bulk-sync#6]
When I am trying to run following code, I am getting error like this 

> Manager' object has no attribute 'bulk_update'

`ret = bulk_sync(
                new_models=new_models,
                filters=filters,
                key_fields=key_fields)`

**Comment by ses4j** [comment]
@manojsitapara Can you provide a more complete stack trace? Also, include python, Django, and library versions.

**Comment by ses4j** [comment]
@manojsitapara ... but probably, you're using a Django version less than 2.2.  If so, use a 1.x release: 
`pip install -U django-bulk-sync==1.3.1` as Django <2.2 support was dropped in the 2.x series (as documented in README).

**Comment by ses4j** [comment]
Closing due to staleness.  @manojsitapara reopen if I missed something.
